### ISSUE TITLE
Unable to run module for IOS in Titanium SDK 3.4.0 GA.

### ISSUE THREAD

**Issue by ravivarma434** [benbahrenburg/Ti.JBChart#3]
Hi,

Please help me in using module in SDK 3.4.0 GA and above. Following is the error we are facing when app is running with module.

Error : "Module ti.jbchart version 1.0 is missing library file: /Users/apps/Library/Application Support/Titanium/modules/iphone/ti.jbchart/1.0/libti.jbchart.a" while trying to use "ti.jbchart"

Please help me in this issue.

Thanks in Advance.

**Comment by benbahrenburg** [comment]
You will need to use version 0.4 and Ti SDK 3.5.0.GA
